name: declaration_naissance
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_secure_storage: ^9.2.4

  connectivity_plus: ^6.1.5

  intl: ^0.20.2

  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.6
  path: ^1.9.0

  crypto: ^3.0.3

  provider: ^6.1.5+1

  animations: ^2.0.11
  font_awesome_flutter: ^10.10.0
  flutter_staggered_animations: ^1.1.0
  badges: ^3.1.2
  liquid_progress_indicator: ^0.4.0
  shimmer: ^3.0.0
  carousel_slider: ^5.1.1

  image_picker: ^1.2.0
  http: ^1.2.1

  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  firebase_app_check: ^0.4.0+1

  google_sign_in: ^7.1.1

  local_auth: ^2.1.7

  face_camera: ^0.1.4
  package_info_plus: ^8.0.0
  camera: ^0.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
