// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtAMgS6Om-XRSROxu86PrnIV7XlXGYCkI',
    appId: '1:95444634348:web:c0c39c88317c6dc00cf3c9',
    messagingSenderId: '95444634348',
    projectId: 'etatcivil-d7daa',
    authDomain: 'etatcivil-d7daa.firebaseapp.com',
    storageBucket: 'etatcivil-d7daa.firebasestorage.app',
    measurementId: 'G-8944RBSLH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBrmajP5AwcRnJJNEqh1QaThsPdhb_CYA',
    appId: '1:95444634348:android:ffb41341a20a91310cf3c9',
    messagingSenderId: '95444634348',
    projectId: 'etatcivil-d7daa',
    storageBucket: 'etatcivil-d7daa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_KUieYMsI4mGepPRhOzbkejMHGL4MfaM',
    appId: '1:95444634348:ios:6acfeed5381213690cf3c9',
    messagingSenderId: '95444634348',
    projectId: 'etatcivil-d7daa',
    storageBucket: 'etatcivil-d7daa.firebasestorage.app',
    iosBundleId: 'com.example.declarationNaissance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_KUieYMsI4mGepPRhOzbkejMHGL4MfaM',
    appId: '1:95444634348:ios:6acfeed5381213690cf3c9',
    messagingSenderId: '95444634348',
    projectId: 'etatcivil-d7daa',
    storageBucket: 'etatcivil-d7daa.firebasestorage.app',
    iosBundleId: 'com.example.declarationNaissance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtAMgS6Om-XRSROxu86PrnIV7XlXGYCkI',
    appId: '1:95444634348:web:cf2899974f7c11bb0cf3c9',
    messagingSenderId: '95444634348',
    projectId: 'etatcivil-d7daa',
    authDomain: 'etatcivil-d7daa.firebaseapp.com',
    storageBucket: 'etatcivil-d7daa.firebasestorage.app',
    measurementId: 'G-4JN1WS71CE',
  );
}
